[package]
name = "discord_simple_tts_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
gtts = "0.1.0"
# serenity = "0.11"
serenity = { version = "0.11", default-features = true }
songbird = "0.3.0"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread", "signal"] }
tts = "0.24.3"
